
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mes_db
      POSTGRES_USER: mes_admin
      POSTGRES_PASSWORD: mes_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mes_admin:mes_password@postgres:5432/mes_db
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: